name: Fork

on:
  workflow_dispatch:

jobs:
  fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.5.1
      - run: forge test
        env:
          FOUNDRY_PROFILE: fork
